/**
 * @description Cyber Truck
 * @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
 * @note        Auto-generated by: https://github.com/pmndrs/gltfjsx
 * @note        Command: `npx gltfjsx@6.5.3 -t public/model/cybertruck.gltf`
 */
import * as THREE from 'three'
import {useFrame} from '@react-three/fiber'
import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import type {CyberTruck as CyberTruckType} from '../../types'
import './cyber-truck/BodyMaterial.tsx'
import {CyberTruckBodyMaterial} from './cyber-truck/BodyMaterial.tsx'

export const CyberTruck = (props: React.JSX.IntrinsicElements['group']) => {
  const meshRef = useRef<THREE.Mesh>(null)

  useFrame((state) => {
    if (!meshRef.current) {
      return
    }

    const material = meshRef.current
      .material as unknown as typeof CyberTruckBodyMaterial & {uTime: number}
    material.uTime = state.clock.getElapsedTime()
  })

  const {nodes, materials} = useGLTF(
    '/r3f-cyber-truck-shader/model/cybertruck.gltf',
  ) as unknown as CyberTruckType
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow={true}
        geometry={nodes.steer.geometry}
        material={materials.gray}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001.geometry}
        material={materials.lights}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001_1.geometry}
        material={materials.body}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001_2.geometry}
        material={materials.glass}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001_3.geometry}
        material={materials.glassframes}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001_4.geometry}
        material={materials.warninglights}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001_5.geometry}
        material={materials.body}
      />
      <mesh
        ref={meshRef}
        castShadow={true}
        geometry={nodes.interior001_6.geometry}
      >
        <cyberTruckBodyMaterial transparent={true} />
      </mesh>
      <mesh
        castShadow={true}
        geometry={nodes.tires001.geometry}
        material={materials.tires}
      />
      <mesh
        castShadow={true}
        geometry={nodes.tires001_1.geometry}
        material={materials.rims}
      />
    </group>
  )
}

useGLTF.preload('/r3f-cyber-truck-shader/model/cybertruck.gltf')
