/**
 * @description Cyber Truck
 * @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
 * @note        Auto-generated by: https://github.com/pmndrs/gltfjsx
 * @note        Command: `npx gltfjsx@6.5.3 -t public/model/cybertruck.gltf`
 */
import React from 'react'
import * as THREE from 'three'
import {useGLTF} from '@react-three/drei'
import {type GLTF} from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    interior001: THREE.Mesh
    interior001_1: THREE.Mesh
    interior001_2: THREE.Mesh
    interior001_3: THREE.Mesh
    interior001_4: THREE.Mesh
    interior001_5: THREE.Mesh
    interior001_6: THREE.Mesh
    steer: THREE.Mesh
    tires001: THREE.Mesh
    tires001_1: THREE.Mesh
  }
  materials: {
    lights: THREE.MeshStandardMaterial
    body: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
    glassframes: THREE.MeshStandardMaterial
    warninglights: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    shader: THREE.MeshStandardMaterial
    gray: THREE.MeshStandardMaterial
    tires: THREE.MeshStandardMaterial
    rims: THREE.MeshStandardMaterial
  }
}

export const CyberTruck = (props: React.JSX.IntrinsicElements['group']) => {
  const {nodes, materials} = useGLTF(
    '/r3f-cyber-truck-shader/model/cybertruck.gltf',
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow={true}
        geometry={nodes.steer.geometry}
        material={materials.gray}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001.geometry}
        material={materials.lights}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001_1.geometry}
        material={materials.body}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001_2.geometry}
        material={materials.glass}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001_3.geometry}
        material={materials.glassframes}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001_4.geometry}
        material={materials.warninglights}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001_5.geometry}
        material={materials.black}
      />
      <mesh
        castShadow={true}
        geometry={nodes.interior001_6.geometry}
        material={materials.shader}
      />
      <mesh
        castShadow={true}
        geometry={nodes.tires001.geometry}
        material={materials.tires}
      />
      <mesh
        castShadow={true}
        geometry={nodes.tires001_1.geometry}
        material={materials.rims}
      />
    </group>
  )
}

useGLTF.preload('/r3f-cyber-truck-shader/model/cybertruck.gltf')
